### PR TITLE
Updating the build.gradle for the agent, core, and web projects to us…

### PR DESCRIPTION
**Pull request by JRiggenbach**
…e the latest version of compile dependencies.  Reason was to see if updating to the latest dependencies would help improve a Veracode score, which it did.

Fix # .

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by JRiggenbach** [comment]
Josh Riggenbach from McKesson submitting a pull request to update the gradle files to move to the latest version of some compile dependencies that address issues that are flagged by our security (Veracode) scan.  We are currently running with this updated jars that the build produced and have not seen any unexpected behaviors.

**Comment by Dmitry-Matveev** [comment]
Thanks, @JRiggenbach! We appreciate the contribution and are glad it's working for you while addressing Veracode findings.
Please note that we'd need to run those new versions through the approval process first before we ship with them, so it might take some time.

**Comment by dhaval24** [comment]
@Dmitry-Matveev do we need to address this as a part of Java SDL?

**Comment by Dmitry-Matveev** [comment]
If we got OSS approval for the packages mentioned in this PR we should've merged it for 1.0.10 already.
Yes, it's absolutely goes in hand with Security Development Lifecycle as those were findings by Veracode security scan.

**Comment by dhaval24** [comment]
@Dmitry-Matveev yes we have already received OSS approvals for the packages mentioned in the above PR. I don't know for some reason it isn't merged yet I will merge this.

**Comment by dhaval24** [comment]
@grlima this is a security issue fixed by one of our users and we should address this by merging this PR.

**Comment by dhaval24** [comment]
@JRiggenbach please have a look at this PR  : #473 (we have merged this one to update to the latest dependencies, and hence I am closing this one). I really appreciate your concern here and hopefully this should eliminate any of the issues you were facing with Application Insights java SDK. Also please have a a look at #468 #469. We are planning the Beta SDK release pattern and your support towards this initiative would be greatly appreciated if possible.

**Pull request closed without merging**
