### PR TITLE
Add default log message

### PR DESCRIPTION
**Pull request by trask**
@rajkumar-rangaraj @vishweshbankwar is there already a standard way of handling empty messages in Application Insights .NET SDK?

### CODE REVIEW

**Comment by vishweshbankwar** [comment]
@trask - it replaces it with "n/a" 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/BASE/src/Microsoft.ApplicationInsights/DataContracts/TraceTelemetry.cs#L201

https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/BASE/Test/Microsoft.ApplicationInsights.Test/Microsoft.ApplicationInsights.Tests/DataContracts/TraceTelemetryTest.cs#L128

**Comment by trask** [comment]
@vishweshbankwar perfect! we will do the same here

**Comment by trask** [comment]
cc: @lzchen @hectorhdzg

**Comment by lzchen** [comment]
What does this change pertain to?

**Review by heyams — APPROVED** [review]

**Pull request merged**
