### PR TITLE
Test exception change

### PR DESCRIPTION
**Pull request by trask**
Testing https://github.com/Azure/azure-sdk-for-java/pull/41397

### CODE REVIEW

**Comment by heyams** [comment]
do we need to update our log exception and event exception smoke tests to capture `exception.type` and `exception.message`?

**Comment by heyams** [comment]
@trask do you think i can ask that customer to try this new snapshot?

**Comment by trask** [comment]
TODO first add assertions on exception type name for all smoke tests that check exception message (in a separate PR)

**Comment by heyams** [comment]
i approved the azure-sdk PR. you can close this now.

**Pull request closed without merging**
